### ISSUE TITLE
Hello, would you kindly remind where the ``observation class`` of the simulation environment is defined?

### ISSUE THREAD

**Issue by Yonggie** [rllab-snu/TopologicalSemanticGraphMemory#11]
Hello, would you kindly point out where the ``observation class`` of the simulation environment is defined?

We see different kind of informaiton is given by the observation space. Would you mind give a hint where we can find the observation space (the ``observation`` dict keys) config file/definition file or code?
![图片](https://github.com/rllab-snu/TopologicalSemanticGraphMemory/assets/31330044/16c3684c-41d8-46e8-936a-34b1cbc63907)

**Comment by ChonghaoCheng** [comment]
![image](https://github.com/rllab-snu/TopologicalSemanticGraphMemory/assets/36367930/480eff6c-5a3b-4e7b-8c9f-6fcb04cc00c0)

Hello It seems like the `obj_dict` is quite  similiar to this question here. And would you please explain the meaning of the observation dict keys ?

**Comment by bareblackfoot** [comment]
Sorry for the late reply.
As i remember, the ImageGoalEnv inherits the gym environment and it needs observation space to be predefined like the picture of the comment of @SDUEricCheng. 
Its just a dictionary about the observations and not class.
