### ISSUE TITLE
Can you share me the link of gibson's scene_set?

### ISSUE THREAD

**Issue by kvkcon** [rllab-snu/TopologicalSemanticGraphMemory#14]
/data/polaris/vln_simulation/habitat-lab-v21/habitat/../data/scene_datasets/gibson/Cantwell/Cantwell.glb does not correspond to any existing file or primitive render asset. 
When I run evaluate.py, the error occurs. I guess I downloaded the scene_set of gibson wrong. Can you share me the link of gibson's scene_set?

**Comment by calcualatexzy** [comment]
Same question here, I found gibson kind of disordered here. I downloaded the gibson habitat_trainval dataset but it somewhat mismatches your the gibson_floorplans, and I converted the semantic information but it still is not 100% matching the gibson dataset. May you teach me how to deal with this?
Could you please note how specifically you downloaded your gibson(gibson_tiny) please?
And by the way, where did you placed your semantic data? I didn't see any details of this piece of data in your README note, thankyou!

**Comment by kvkcon** [comment]
I download pointnav-dataset and I find
it matches with gibson_hhabitat_ttrainval.zip
















KvKcon
***@***.***


---Original---
From: "Ziyi ***@***.***&gt;
Date: Fri, Dec 15, 2023 15:58 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [rllab-snu/TopologicalSemanticGraphMemory] Can you share me thelink of gibson's scene_set? (Issue #14)




 
Same question here, I found gibson kind of disordered here. I downloaded the gibson habitat_trainval dataset but it somewhat mismatches your the gibson_floorplans, and I converted the semantic information but it still is not 100% matching the gibson dataset. May you teach me how to deal with this?
 Could you please note how specifically you downloaded your gibson(gibson_tiny) please?
 And by the way, where did you placed your semantic data? I didn't see any details of this piece of data in your README note, thankyou!

**Comment by calcualatexzy** [comment]
> I download pointnav-dataset and I find it matches with gibson_hhabitat_ttrainval.zip KvKcon ***@***.***
> […](#)
> ---Original--- From: "Ziyi ***@***.***&gt; Date: Fri, Dec 15, 2023 15:58 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [rllab-snu/TopologicalSemanticGraphMemory] Can you share me thelink of gibson's scene_set? (Issue #14) Same question here, I found gibson kind of disordered here. I downloaded the gibson habitat_trainval dataset but it somewhat mismatches your the gibson_floorplans, and I converted the semantic information but it still is not 100% matching the gibson dataset. May you teach me how to deal with this? Could you please note how specifically you downloaded your gibson(gibson_tiny) please? And by the way, where did you placed your semantic data? I didn't see any details of this piece of data in your README note, thankyou! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

oops I rechecked the dataset, I think the 1.5GB gibson dataset(not the trainval one, but gibson_habitat one below)  is what we need. It matches the floorplans and the pointnav, and i think it was what they used. But Im still confused of how to use the semantic data.
As a noob in the field, thanks for the reply though.

**Comment by bareblackfoot** [comment]
You can download the gibson semantic data from [this link](https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#gibson-and-3dscenegraph-datasets)
