### ISSUE TITLE
Demo notebook code causes segmentation fault

### ISSUE THREAD

**Issue by mlodel** [rllab-snu/TopologicalSemanticGraphMemory#16]
I am trying to run the code in `demo/build_tsgm_demo.ipynb` to understand the basic workings of your framework. However, the line `sim = habitat_sim.Simulator(cfg)` causes a `125666 segmentation fault (core dumped)`. I checked that the gibson scene loaded in `settings["scene"]` exists, and double checked all dependencies for habitat-sim (even built it from source).
The issue has persistent when trying to reproduce the entire setup in a docker both for conda-installed and source-built habitat-sim, so the issue is likely in the code.

I see that the `make_cfg` function is not used in any of the other scripts. Is there a chance that some part of how the simulator is created in the demo notebook is not consistent anymore, that has been updated in the meantime? Or did you encounter such problems in the past? It's hard to debug the segmentation fault, I will try that later.

Thank you for any help!

**Comment by bareblackfoot** [comment]
Hello, Thanks for your interest in our work :).
I think habitat version is mismatched. please downgrade the habitat version. 
Thanks

**Comment by mlodel** [comment]
@bareblackfoot Thanks for the response! I installed the habitat version 0.2.1 for sim and lab. Do I need a different version for the demo notebook?
