### ISSUE TITLE
maps_topdown_object

### ISSUE THREAD

**Issue by leyuan-sun** [rllab-snu/TopologicalSemanticGraphMemory#3]
I cannot find the img list star_yellow,blue in maps_topdown_object this unexist folder.

**Comment by bareblackfoot** [comment]
You can download the assets from this [link](https://mysnu-my.sharepoint.com/:f:/g/personal/blackfoot_seoul_ac_kr/Eo5Ux_4ftT5Dic5fJa8h9yYBiCuVZ2pxZHjtYEn6Z_lHgg?e=Gbu844).
