### ISSUE TITLE
No such file or directory: './data/episodes/VGM/gibson/Cantwell_easy.json'

### ISSUE THREAD

**Issue by XiaohanLei** [rllab-snu/TopologicalSemanticGraphMemory#5]
Hi!
It seems that the link you provided doesn't contain the file mentioned in the title.
If possible, could you give me more guidance about the episode files.
Thanks in advance!

**Comment by bareblackfoot** [comment]
I updated the download link to contain the episodes files :)
You can download them [here](https://mysnu-my.sharepoint.com/:f:/g/personal/blackfoot_seoul_ac_kr/ElnvlmlZA8dPrFWU7Vsu1tAB-EX9EKW9_axWXYoFQEZCow?e=Kv2zl2).
