### ISSUE TITLE
The Img_encoder pre-trained model might be corrupted

### ISSUE THREAD

**Issue by JeffreyYH** [rllab-snu/TopologicalSemanticGraphMemory#6]
Hi,

Thanks for open-sourcing the excellent work!

However when I run the code with Img_encoder.pth.tar, it shows `RuntimeError: unexpected EOF, expected 757379 more bytes. The file might be corrupted.` Maybe there's something wrong with the model? I'd be appreciated if you might re-upload it.

Thank you!

**Comment by bareblackfoot** [comment]
Hmmm I don't know why but after calling the model in the code, the file size become smaller and the pytorch package say that it is corrupted. 
I uploaded another model, please use it, although i am not sure that it would work :(
I will check it on weekend.

Thank you :)

**Comment by JeffreyYH** [comment]
Thank you so much!

**Comment by bareblackfoot** [comment]
I updated files and codes to fix errors :)
Please check it out 😉
